Create no_no.json
Worker20/CreateRobotics-1.18 pull request #42
Opened 2023-06-23 20:16 UTC by Garluss

English translated to Norsk Bokmål
- Garluss

2023-06-25 18:46 UTC, OutCraft-Mods requested changes
Hi, everything great, I just have two small suggestions.
Could you look into them?

2023-06-25 18:46 UTC, OutCraft-Mods commented on src/main/resources/assets/robotics/lang/no_no.json
> +  "item.robotics.code_drone": "Kodedrone",
The Name of the Code Drone is Juan, I'd suggest leaving it as-is:
```suggestion
  "item.robotics.code_drone": "Juan",
```

2023-06-25 18:46 UTC, OutCraft-Mods commented on src/main/resources/assets/robotics/lang/no_no.json
> +  "_": "->------------------------]  Spill Elementer  [------------------------<-",
Nothing big, there's a `{` missing here:
```suggestion
{
  "_": "->------------------------]  Spill Elementer  [------------------------<-",
```

2023-06-25 20:37 UTC, Garluss commented
I will change it when I have time

søn. 25. jun. 2023, 20:47 skrev OutCraft ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Hi, everything great, I just have two small suggestions.
> Could you look into them?
> ------------------------------
>
> In src/main/resources/assets/robotics/lang/no_no.json
> <https://github.com/Worker20/CreateRobotics/pull/42#discussion_r1241262293>
> :
>
> > +  "block.robotics.bronze_block": "Bronseblokk",
> +  "block.robotics.code_editor": "Koderedigerer",
> +  "block.robotics.deepslate_tin_ore": "Tinnmalm i dypskifer",
> +  "block.robotics.smasher": "Knuser",
> +  "block.robotics.tin_block": "Tinnblokk",
> +  "block.robotics.tin_ore": "Tinnmalm",
> +
> +  "entity.robotics.clockcopter": "Klokkekopter",
> +  "entity.robotics.code_drone": "Kodedrone",
> +  "entity.robotics.extend_o_boots": "Ekstend O Støvler",
> +  "entity.robotics.miner": "Gruvearbeider",
> +
> +  "item.robotics.bronze_ingot": "Bronsebarre",
> +  "item.robotics.bronze_nugget": "Bronseklump",
> +  "item.robotics.clockcopter": "Klokkekopter",
> +  "item.robotics.code_drone": "Kodedrone",
>
> The Name of the Code Drone is Juan, I'd suggest leaving it as-is:
> ⬇️ Suggested change
>
> -  "item.robotics.code_drone": "Kodedrone",
> +  "item.robotics.code_drone": "Juan",
>
> ------------------------------
>
> In src/main/resources/assets/robotics/lang/no_no.json
> <https://github.com/Worker20/CreateRobotics/pull/42#discussion_r1241262688>
> :
>
> > @@ -0,0 +1,75 @@
> +  "_": "->------------------------]  Spill Elementer  [------------------------<-",
>
> Nothing big, there's a { missing here:
> ⬇️ Suggested change
>
> -  "_": "->------------------------]  Spill Elementer  [------------------------<-",
> +{
> +  "_": "->------------------------]  Spill Elementer  [------------------------<-",
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Worker20/CreateRobotics/pull/42#pullrequestreview-1497162999>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2YPAQHZVOCLCFRM3J2H7K3XNCBSRANCNFSM6AAAAAAZR7VXFU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-29 16:34 UTC, OutCraft-Mods approved these changes

2023-06-29 16:35 UTC, OutCraft-Mods commented
Thank you for translating the Mod and fixing the small issues!

2023-06-29 16:35 UTC, merged